#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

index:
   path: /bonjour
   defaults: { _controller: 'App\Controller\helloWorld::bonjour' }

# first, run composer req annotations
controllers:
    resource: ../src/Controller/
    type: annotation
